- name: Checkout
  uses: actions/checkout@v1

- name: Run API Tests
  id: run-newman
  uses: anthonyvscode/newman-action@v1
  with:
    collection: New Collection.postman_collection.json
    reporters: cli

- name: Output summary to console
  run: echo ${{ steps.run-newman.outputs.summary }}
